export const  FilmDefault = {
    id: 0,
    updatedAt: "",
    name: "",
    filmId: 0,
    domainType: 0,
    description: "",
    year: 0,
    votes: 0,
    score: 0,
    episodes: "",
    drameType: "",
    areas: "",
    likeList: "",
    verticalPoster: "",
    horizontalPoster: "",
    views: 0,
    actors: [],
    categories: [],
    bannerType: [],

}